In [1]:
import pymongo as pmg
import pandas as pd
import datetime as dt
import pymysql
import matplotlib.pyplot as plt
from matplotlib.lines import TICKLEFT, TICKRIGHT, Line2D
from matplotlib.patches import Rectangle
import matplotlib as mpl
import matplotlib.dates as mdate
from datetime import time
from KRData.HKData import HKFuture
import talib as tb
import configparser
from corr import Analyse_CORR as CORR

OK

In [2]:
conf_parser = configparser.ConfigParser()
conf_parser.read( 'conf.ini')
mg_host = conf_parser.get('MGDB', 'host')
mg_user = conf_parser.get('MGDB', 'user')
mg_password = conf_parser.get('MGDB', 'password')
hf=HKFuture(pwd=mg_password,host=mg_host,user=mg_user)
begin='2011-01-01'
dt1=dt.datetime.now()
_fields = ['datetime', 'code', 'open', 'high', 'low', 'close', 'vol','trade_date']
df=hf.get_bars('HSI1201',_fields)
df.head()

,datetime,code,open,high,low,close,trade_date
datetime,,,,,,,
2011-11-30 09:15:00,2011-11-30 09:15:00,HSI1201,18157.0,18157.0,18113.0,18113.0,2011-11-30
2011-11-30 09:17:00,2011-11-30 09:17:00,HSI1201,18131.0,18131.0,18130.0,18130.0,2011-11-30
2011-11-30 09:19:00,2011-11-30 09:19:00,HSI1201,18140.0,18140.0,18140.0,18140.0,2011-11-30
2011-11-30 09:21:00,2011-11-30 09:21:00,HSI1201,18127.0,18127.0,18115.0,18115.0,2011-11-30
2011-11-30 09:28:00,2011-11-30 09:28:00,HSI1201,18107.0,18107.0,18107.0,18107.0,2011-11-30

In [ ]:
df.iterrows

In [45]:
class backtesting():
    #初始化
    def __init__(self,hf:HKFuture,index='HSI'):
        self.hf=hf
        self._DateList=hf.get_main_contract_trade_dates(index)
        self._para={}
        self._res={}
        self._res['macd']=[]
        self._res['ma60']=[]
        self._res['trade']=[]
        pass
        
    #所有产品
    def prod_all(self):
        for k in self._DateList.keys():
            print(k)
            self.prod_test(k)
            
    #按产品测试
    def prod_test(self,prod):
        self.prod_init(prod)
        self._para['prod']=prod
        dt1=dt.time(9,15)
        dt2=dt.time(16,30)
        date_list=self._DateList[prod]
        self.dl=date_list
        for dd in date_list:
            self._para['date']=dd
            date1=str(dd.date())
            df=self._para['df_prod'][self._para['df_prod']['trade_date']==date1]
            if len(df)<2:
                break
            day_only=df.datetime.apply(lambda x:x.time()>=dt1 and x.time()<=dt2 )
            self._para['df1']=df[day_only]
            if len(df[day_only])<2:
                break
#             print(dd,len(df),len(self._para['df1']))
            self.day_loop()
    
    #产品测试初始化
    def prod_init(self,prod):
        _fields = ['datetime', 'code', 'open', 'high', 'low', 'close', 'vol','trade_date']
        df1=self.hf.get_bars(prod,_fields)
        df1['macd'],df1['diff'],df1['dea']=tb.MACD(df1.close.values,fastperiod=6,slowperiod=12,signalperiod=9)
        df1['ma30']=tb.EMA(df1.close.values,timeperiod=30)
        df1['ma60']=tb.EMA(df1.close.values,timeperiod=60)
        df1['chg']=df1['close']-df1['open']
        df1['std60']=tb.STDDEV(df1['chg'].values,timeperiod=60)
        df1['std1']=df1['chg']/df1['std60']
        self._para['df_prod']=df1

    #交易日循环部分
    def day_loop(self):
        self.day_init()
        self.trade_init()
        df=self._para['df1']
        self._para['day_no']=0
        for i,row in df.iterrows():
            self._para['row']=row
            self.loop_calc()
            if self._para['trade_p']['trade_state']==1:
                self.trade_stop()
            elif self._para['trade_p']['trade_state']==0:
                self.trade_open()
            self._para['day_no']+=1
        self.day_end()
        
    #交易日开始前准备
    def day_init(self):
        self._para['ma60_no_over']=0
        self._para['ma60_no_under']=0
        row1=self._para['df1'].iloc[0]
        self._para['macd']={}
        self._para['ma60']={}
        self._para['ma60']['cnt']=1
        self._para['ma60']['begin']=row1['close']
        if row1['close']>=row1['ma60']:
            self._para['ma60']['state']='over'
        else:
            self._para['ma60']['state']='under'
    
    
    #交易日结束
    def day_end(self):
        if self._para['trade_p']['trade_state']==0:
            return
        trade=self._para['trade']
        row=self._para['row']
        if self._para['trade_p']['trade_state']==1:
            trade['close']=row['open']
            trade['close_type']='end'
            
        trade['diff']=trade['close']-trade['open'] if trade['state']=='buy' \
                                            else trade['open']-trade['close']
        trade['prod']=self._para['prod']
        self._res['trade'].append(trade)
        
    
    #计算部分
    def loop_calc(self):
        self.calc_ma60()
#         self.calc_macd()
        
    #计算MA60
    def calc_ma60(self):
        ma60=self._para['ma60']
        row=self._para['row']
        state=0
        if row['close']>=row['ma60'] and ma60['state'] =='under':
            state=1
            self._para['ma60_no_under']+=1
        elif row['close']<row['ma60'] and ma60['state']=='over':
            self._para['ma60_no_over']+=1
            state=2
        else:
            state=0
            ma60['cnt']+=1
        
        if state>0:
            ma60['prod']=self._para['prod']
            ma60['date']=self._para['date']
            ma60['end']=row['close']
            ma60['diff']=ma60['end']-ma60['begin'] if state==2 else ma60['begin']-ma60['end']
            ma60['no']=self._para['ma60_no_over'] if state==2 else self._para['ma60_no_under']
            self._res['ma60'].append(ma60)
#             print(ma60)
            ma60={}
            ma60['state']='over' if state==1 else 'under'
            ma60['begin']=row['close']
            ma60['cnt']=1
        self._para['ma60']=ma60
        
    #计算MACD
    def calc_macd(self):
        macd=self._para['macd']
        row=self._para['row']
        if row['macd']>0 and macd['ref_macd']<=0:
            print(row['datetime'],row['macd'],0)
        elif row['macd']<0 and macd['ref_macd']>=0:
            print(row['datetime'],row['macd'],1)
        
        macd['ref_macd']=row['macd']
        self._para['macd']=macd
        
    #交易部分
    def trade_open(self):
        if self._para['day_no']<=self._para['trade_p']['rec_end']:
            return
        
        trade=self._para['trade']
        trade_p=self._para['trade_p']
        row=self._para['row']
        state=0
        if row['close']>trade['rec_top']:
            trade['state']='buy'
            trade['open']=row['close']
            trade['stop_price']=row['open']-trade_p['stop_diff']
            state=1
        elif row['close']<trade['rec_bottom']:
            trade['state']='sell'
            trade['open']=row['close']
            trade['stop_price']=row['open']+trade_p['stop_diff']
            state=2
        
        if state>0:
            trade_p['trade_state']=1
            trade['date']=self._para['date']
#             trade['open']=row['close']
            trade['open_idx']=self._para['day_no']-trade_p['rec_end']
        self._para['trade']=trade
        self._para['trade_p']=trade_p
    
    #止损
    def trade_stop(self):
        trade=self._para['trade']
        trade_p=self._para['trade_p']
        row=self._para['row']
        if row['close']<trade['stop_price'] and trade['state']=='buy':
            trade['close']=row['close']
            trade['close_type']='stop'
#             trade['diff']=trade['close']-trade['open']
            trade_p['trade_state']=2
        elif row['close']>trade['stop_price'] and trade['state']=='sell':
            trade['close']=row['close']
            trade['close_type']='stop'
#             trade['diff']=trade['open']-trade['close']
            trade_p['trade_state']=2
        self._para['trade_p']=trade_p
        
    #交易的初始部分
    def trade_init(self):
        df1=self._para['df1']
        trade={}
        trade_p={}
        self._para['trade']={}
        self._para['trade_p']={}
        trade_p['rec_begin']=7
        trade_p['rec_len']=60
        trade_p['rec_end']=trade_p['rec_begin']+trade_p['rec_len']-1
        preDF=df1[trade_p['rec_begin']:trade_p['rec_end']]
        IndexList=preDF.index.tolist()
        T_idx=preDF['close'].idxmax()
        B_idx=preDF['close'].idxmin()
        trade['top_idx']=IndexList.index(T_idx)
        trade['bottom_idx']=IndexList.index(B_idx)
        trade['rec_top']=preDF['close'].max()
        trade['rec_bottom']=preDF['close'].min()
        trade['rec_diff']=trade['rec_top']-trade['rec_bottom']
        trade_p['stop_diff']=trade['rec_diff']/2
        trade_p['stop_diff']=40 if trade_p['stop_diff']<40 else trade_p['stop_diff']
        trade_p['stop_diff']=220 if trade_p['stop_diff']>220 else trade_p['stop_diff']
        trade_p['trade_state']=0
        self._para['trade']=trade
        self._para['trade_p']=trade_p
print("OK")

OK

In [46]:
time1=dt.datetime.now()
print(time1)
test=backtesting(hf)
# test.prod_test('HSI1109')
test.prod_all()
time2=dt.datetime.now()
print(time2-time1)
# test._res['ma60']

2019-05-19 15:06:00.007438
HSI1101
HSI1102
HSI1103
HSI1104
HSI1105
HSI1106
HSI1107
HSI1108
HSI1109
HSI1110
HSI1111
HSI1112
HSI1201
HSI1202
HSI1203
HSI1204
HSI1205
HSI1206
HSI1207
HSI1208
HSI1209
HSI1210
HSI1211
HSI1212
HSI1301
HSI1302
HSI1303
HSI1304
HSI1305
HSI1306
HSI1307
HSI1308
HSI1309
HSI1310
HSI1311
HSI1312
HSI1401
HSI1402
HSI1403
HSI1404
HSI1405
HSI1406
HSI1407
HSI1408
HSI1409
HSI1410
HSI1411
HSI1412
HSI1501
HSI1502
HSI1503
HSI1504
HSI1505
HSI1506
HSI1507
HSI1508
HSI1509
HSI1510
HSI1511
HSI1512
HSI1601
HSI1602
HSI1603
HSI1604
HSI1605
HSI1606
HSI1607
HSI1608
HSI1609
HSI1610
HSI1611
HSI1612
HSI1701
HSI1702
HSI1703
HSI1704
HSI1705
HSI1706
HSI1707
HSI1708
HSI1709
HSI1710
HSI1711
HSI1712
HSI1801
HSI1802
HSI1803
HSI1804
HSI1805
HSI1806
HSI1807
HSI1808
HSI1809
HSI1810
HSI1811
HSI1812
HSI1901
HSI1902
HSI1903
HSI1904
HSI1905
0:03:12.646973

In [254]:
time1=dt.datetime.now()
print(time1)
test=backtesting(hf,index='HHI')
# test.prod_test('HSI1109')
test.prod_all()
time2=dt.datetime.now()
print(time2-time1)
# test._res['ma60']

2019-05-19 02:04:29.553804
HHI1101

NameError: name 't_para' is not defined

In [43]:
time1=dt.datetime.now()
print(time1)
test=backtesting(hf)
test.prod_test('HSI1903')
# test.prod_all()
time2=dt.datetime.now()
print(time2-time1)
test._res['trade']

2019-05-19 15:03:26.671738
0:00:32.793990

[{'top_idx': 52,
  'bottom_idx': 5,
  'rec_top': 28884.0,
  'rec_bottom': 28660.0,
  'rec_diff': 224.0,
  'state': 'buy',
  'open': 28903.0,
  'stop_price': 28761.0,
  'date': datetime.datetime(2019, 2, 28, 0, 0),
  'open_idx': 24,
  'close': 28747.0,
  'close_type': 'stop',
  'diff': -156.0,
  'prod': 'HSI1903'},
 {'top_idx': 23,
  'bottom_idx': 14,
  'rec_top': 28758.0,
  'rec_bottom': 28672.0,
  'rec_diff': 86.0,
  'state': 'buy',
  'open': 28760.0,
  'stop_price': 28713.0,
  'date': datetime.datetime(2019, 3, 1, 0, 0),
  'open_idx': 22,
  'close': 28707.0,
  'close_type': 'stop',
  'diff': -53.0,
  'prod': 'HSI1903'},
 {'top_idx': 58,
  'bottom_idx': 9,
  'rec_top': 28826.0,
  'rec_bottom': 28734.0,
  'rec_diff': 92.0,
  'state': 'buy',
  'open': 28833.0,
  'stop_price': 28776.0,
  'date': datetime.datetime(2019, 3, 4, 0, 0),
  'open_idx': 6,
  'close': 28874.0,
  'close_type': 'end',
  'diff': 41.0,
  'prod': 'HSI1903'},
 {'top_idx': 15,
  'bottom_idx': 2,
  'rec_top': 28801.0,
  'rec_bottom': 28686.0,
  'rec_diff': 115.0,
  'state': 'buy',
  'open': 28812.0,
  'stop_price': 28719.5,
  'date': datetime.datetime(2019, 3, 5, 0, 0),
  'open_idx': 15,
  'close': 28903.0,
  'close_type': 'end',
  'diff': 91.0,
  'prod': 'HSI1903'},
 {'top_idx': 29,
  'bottom_idx': 5,
  'rec_top': 29065.0,
  'rec_bottom': 28876.0,
  'rec_diff': 189.0,
  'state': 'buy',
  'open': 29071.0,
  'stop_price': 28969.5,
  'date': datetime.datetime(2019, 3, 6, 0, 0),
  'open_idx': 18,
  'close': 28964.0,
  'close_type': 'stop',
  'diff': -107.0,
  'prod': 'HSI1903'},
 {'top_idx': 45,
  'bottom_idx': 18,
  'rec_top': 28993.0,
  'rec_bottom': 28878.0,
  'rec_diff': 115.0,
  'state': 'sell',
  'open': 28822.0,
  'stop_price': 28943.5,
  'date': datetime.datetime(2019, 3, 7, 0, 0),
  'open_idx': 44,
  'close': 28734.0,
  'close_type': 'end',
  'diff': 88.0,
  'prod': 'HSI1903'},
 {'top_idx': 56,
  'bottom_idx': 8,
  'rec_top': 28423.0,
  'rec_bottom': 28312.0,
  'rec_diff': 111.0,
  'state': 'buy',
  'open': 28426.0,
  'stop_price': 28337.5,
  'date': datetime.datetime(2019, 3, 8, 0, 0),
  'open_idx': 5,
  'close': 28336.0,
  'close_type': 'stop',
  'diff': -90.0,
  'prod': 'HSI1903'},
 {'top_idx': 39,
  'bottom_idx': 0,
  'rec_top': 28343.0,
  'rec_bottom': 28227.0,
  'rec_diff': 116.0,
  'state': 'buy',
  'open': 28349.0,
  'stop_price': 28281.0,
  'date': datetime.datetime(2019, 3, 11, 0, 0),
  'open_idx': 35,
  'close': 28487.0,
  'close_type': 'end',
  'diff': 138.0,
  'prod': 'HSI1903'},
 {'top_idx': 23,
  'bottom_idx': 8,
  'rec_top': 28856.0,
  'rec_bottom': 28755.0,
  'rec_diff': 101.0,
  'state': 'buy',
  'open': 28857.0,
  'stop_price': 28788.5,
  'date': datetime.datetime(2019, 3, 12, 0, 0),
  'open_idx': 3,
  'close': 28915.0,
  'close_type': 'end',
  'diff': 58.0,
  'prod': 'HSI1903'},
 {'top_idx': 6,
  'bottom_idx': 58,
  'rec_top': 28945.0,
  'rec_bottom': 28756.0,
  'rec_diff': 189.0,
  'state': 'sell',
  'open': 28746.0,
  'stop_price': 28849.5,
  'date': datetime.datetime(2019, 3, 13, 0, 0),
  'open_idx': 3,
  'close': 28862.0,
  'close_type': 'stop',
  'diff': -116.0,
  'prod': 'HSI1903'},
 {'top_idx': 23,
  'bottom_idx': 14,
  'rec_top': 28944.0,
  'rec_bottom': 28827.0,
  'rec_diff': 117.0,
  'state': 'sell',
  'open': 28818.0,
  'stop_price': 28892.5,
  'date': datetime.datetime(2019, 3, 14, 0, 0),
  'open_idx': 66,
  'close': 28898.0,
  'close_type': 'stop',
  'diff': -80.0,
  'prod': 'HSI1903'},
 {'top_idx': 55,
  'bottom_idx': 0,
  'rec_top': 29040.0,
  'rec_bottom': 28846.0,
  'rec_diff': 194.0,
  'state': 'buy',
  'open': 29047.0,
  'stop_price': 28944.0,
  'date': datetime.datetime(2019, 3, 15, 0, 0),
  'open_idx': 6,
  'close': 29038.0,
  'close_type': 'end',
  'diff': -9.0,
  'prod': 'HSI1903'},
 {'top_idx': 45,
  'bottom_idx': 20,
  'rec_top': 29196.0,
  'rec_bottom': 29066.0,
  'rec_diff': 130.0,
  'state': 'buy',
  'open': 29198.0,
  'stop_price': 29129.0,
  'date': datetime.datetime(2019, 3, 18, 0, 0),
  'open_idx': 6,
  'close': 29391.0,
  'close_type': 'end',
  'diff': 193.0,
  'prod': 'HSI1903'},
 {'top_idx': 16,
  'bottom_idx': 37,
  'rec_top': 29494.0,
  'rec_bottom': 29385.0,
  'rec_diff': 109.0,
  'state': 'sell',
  'open': 29377.0,
  'stop_price': 29447.5,
  'date': datetime.datetime(2019, 3, 19, 0, 0),
  'open_idx': 72,
  'close': 29449.0,
  'close_type': 'stop',
  'diff': -72.0,
  'prod': 'HSI1903'},
 {'top_idx': 3,
  'bottom_idx': 45,
  'rec_top': 29398.0,
  'rec_bottom': 29272.0,
  'rec_diff': 126.0,
  'state': 'buy',
  'open': 29399.0,
  'stop_price': 29330.0,
  'date': datetime.datetime(2019, 3, 20, 0, 0),
  'open_idx': 31,
  'close': 29314.0,
  'close_type': 'stop',
  'diff': -85.0,
  'prod': 'HSI1903'},
 {'top_idx': 28,
  'bottom_idx': 16,
  'rec_top': 29451.0,
  'rec_bottom': 29353.0,
  'rec_diff': 98.0,
  'state': 'buy',
  'open': 29472.0,
  'stop_price': 29396.0,
  'date': datetime.datetime(2019, 3, 21, 0, 0),
  'open_idx': 16,
  'close': 29383.0,
  'close_type': 'stop',
  'diff': -89.0,
  'prod': 'HSI1903'},
 {'top_idx': 14,
  'bottom_idx': 52,
  'rec_top': 29262.0,
  'rec_bottom': 29098.0,
  'rec_diff': 164.0,
  'state': 'sell',
  'open': 29085.0,
  'stop_price': 29194.0,
  'date': datetime.datetime(2019, 3, 22, 0, 0),
  'open_idx': 9,
  'close': 29075.0,
  'close_type': 'end',
  'diff': 10.0,
  'prod': 'HSI1903'},
 {'top_idx': 44,
  'bottom_idx': 0,
  'rec_top': 28654.0,
  'rec_bottom': 28454.0,
  'rec_diff': 200.0,
  'state': 'buy',
  'open': 28670.0,
  'stop_price': 28553.0,
  'date': datetime.datetime(2019, 3, 25, 0, 0),
  'open_idx': 12,
  'close': 28550.0,
  'close_type': 'stop',
  'diff': -120.0,
  'prod': 'HSI1903'},
 {'top_idx': 5,
  'bottom_idx': 30,
  'rec_top': 28719.0,
  'rec_bottom': 28594.0,
  'rec_diff': 125.0,
  'state': 'sell',
  'open': 28572.0,
  'stop_price': 28659.5,
  'date': datetime.datetime(2019, 3, 26, 0, 0),
  'open_idx': 41,
  'close': 28539.0,
  'close_type': 'end',
  'diff': 33.0,
  'prod': 'HSI1903'},
 {'top_idx': 32,
  'bottom_idx': 8,
  'rec_top': 28673.0,
  'rec_bottom': 28547.0,
  'rec_diff': 126.0,
  'state': 'buy',
  'open': 28686.0,
  'stop_price': 28608.0,
  'date': datetime.datetime(2019, 3, 27, 0, 0),
  'open_idx': 11,
  'close': 28680.0,
  'close_type': 'end',
  'diff': -6.0,
  'prod': 'HSI1903'},
 {'top_idx': 58,
  'bottom_idx': 28,
  'rec_top': 28676.0,
  'rec_bottom': 28573.0,
  'rec_diff': 103.0,
  'state': 'buy',
  'open': 28688.0,
  'stop_price': 28623.5,
  'date': datetime.datetime(2019, 3, 28, 0, 0),
  'open_idx': 1,
  'close': 28718.0,
  'close_type': 'end',
  'diff': 30.0,
  'prod': 'HSI1903'}]

In [52]:
Calc=['sum','count','mean','std','max','min']
f1=pd.DataFrame(test._res['trade'])
f1['diff'].agg(Calc)
f1.groupby(['state','close_type'])['diff'].agg(Calc)
f1.groupby(['state'])['diff'].agg(Calc)
f1.head()

,bottom_idx,close,close_type,date,diff,open,open_idx,prod,rec_bottom,rec_diff,rec_top,state,stop_price,top_idx
0,17,23371.0,end,2011-01-03,11.0,23360.0,2,HSI1101,23076.0,277.0,23353.0,buy,23212.5,58
1,11,23661.0,end,2011-01-04,104.0,23557.0,10,HSI1101,23407.0,145.0,23552.0,buy,23467.5,34
2,4,23758.0,end,2011-01-05,27.0,23731.0,141,HSI1101,23592.0,117.0,23709.0,buy,23632.5,38
3,42,23814.0,stop,2011-01-06,-88.0,23726.0,3,HSI1101,23743.0,91.0,23834.0,sell,23795.5,24
4,11,23730.0,stop,2011-01-07,-124.0,23854.0,31,HSI1101,23710.0,139.0,23849.0,buy,23771.5,45

In [239]:
Calc=['sum','count','mean','std','max','min']
f1=pd.DataFrame(test._res['ma60'])
f1.groupby(['no'])['diff'].agg(Calc)
f1[f1.state=='under'].groupby(['no'])['diff'].agg(Calc)
# f1.head()

       sum  count      mean        std    max    min
no
1   3156.0   2014  1.567031  47.386460  561.0 -163.0
2  -1972.0   2012 -0.980119  25.803904  529.0  -57.0
3    595.0   2003  0.297054  26.363916  347.0 -143.0
4  -1015.0   1991 -0.509794  21.464562  304.0  -57.0
5      3.0   1971  0.001522  23.288578  298.0  -61.0
6  -1827.0   1933 -0.945163  18.963108  225.0  -46.0
7   -586.0   1894 -0.309398  23.199549  390.0  -38.0
8  -3075.0   1825 -1.684932  16.734181  359.0  -44.0
9  -2827.0   1732 -1.632217  14.683739  167.0 -211.0
10 -3407.0   1622 -2.100493  13.250927  178.0  -48.0
11 -2399.0   1484 -1.616577  15.615466  343.0  -41.0
12 -3269.0   1340 -2.439552  11.073928  110.0  -40.0
13 -2487.0   1207 -2.060481  11.525176  126.0  -51.0
14 -1824.0   1049 -1.738799  13.547782  187.0  -36.0
15 -2271.0    907 -2.503859   9.956680  107.0  -26.0
16 -1671.0    750 -2.228000   9.831424  117.0  -25.0
17 -1536.0    596 -2.577181   9.098846  105.0  -42.0
18 -1096.0    485 -2.259794   9.424259   98.0  -23.0
19  -901.0    379 -2.377309   7.673055   85.0  -25.0
20  -820.0    287 -2.857143   7.855145   72.0  -37.0
21  -526.0    199 -2.643216  14.216875  179.0  -38.0
22  -544.0    142 -3.830986   7.215991   44.0  -30.0
23  -323.0     95 -3.400000   3.092200    2.0  -17.0
24  -286.0     72 -3.972222   3.653947    8.0  -14.0
25   -74.0     43 -1.720930   9.029912   33.0  -21.0
26   -95.0     30 -3.166667   5.837355   21.0  -14.0
27   -70.0     23 -3.043478   3.197702    2.0   -9.0
28   -47.0     14 -3.357143   1.864946    0.0   -6.0
29   -43.0     10 -4.300000   2.406011   -1.0   -9.0
30    -6.0      6 -1.000000   4.732864    7.0   -7.0
31    -7.0      3 -2.333333   1.154701   -1.0   -3.0
32   -16.0      2 -8.000000   1.414214   -7.0   -9.0

In [222]:
f1=test._para['df_prod']
f2=f1[f1.trade_date==test._para['date']]
dt1=dt.time(9,15)
dt2=dt.time(16,30)
day_only=f2.datetime.apply(lambda x:x.time()>=dt1 and x.time()<=dt2 )
f2

,datetime,code,open,high,low,close,trade_date,macd,diff,dea,ma30,ma60,chg,std60,std1
datetime,,,,,,,,,,,,,,,
2016-08-01 17:15:00,2016-08-01 17:15:00,HSI1608,22114.0,22114.0,22072.0,22080.0,2016-08-02,1.188469,3.995586,-2.807117,22100.842455,22108.265781,-34.0,9.025566,-3.767077
2016-08-01 17:16:00,2016-08-01 17:16:00,HSI1608,22083.0,22086.0,22071.0,22073.0,2016-08-02,-3.136552,2.569158,-5.705710,22099.046167,22107.109526,-10.0,8.859772,-1.128697
2016-08-01 17:17:00,2016-08-01 17:17:00,HSI1608,22072.0,22073.0,22066.0,22066.0,2016-08-02,-6.535782,0.748170,-7.283952,22096.914157,22105.761672,-6.0,8.880065,-0.675671
2016-08-01 17:18:00,2016-08-01 17:18:00,HSI1608,22063.0,22064.0,22055.0,22060.0,2016-08-02,-9.094183,-1.220300,-7.873883,22094.532598,22104.261290,-3.0,7.936886,-0.377982
2016-08-01 17:19:00,2016-08-01 17:19:00,HSI1608,22061.0,22067.0,22058.0,22065.0,2016-08-02,-9.581385,-2.892517,-6.688867,22092.627269,22102.974034,4.0,7.772655,0.514625
2016-08-01 17:20:00,2016-08-01 17:20:00,HSI1608,22067.0,22067.0,22058.0,22058.0,2016-08-02,-10.377764,-4.389567,-5.988198,22090.393252,22101.499476,-9.0,7.671810,-1.173126
2016-08-01 17:21:00,2016-08-01 17:21:00,HSI1608,22057.0,22062.0,22052.0,22062.0,2016-08-02,-9.875455,-5.486744,-4.388710,22088.561429,22100.204411,5.0,7.671810,0.651737
2016-08-01 17:22:00,2016-08-01 17:22:00,HSI1608,22063.0,22063.0,22056.0,22061.0,2016-08-02,-9.269643,-6.243324,-3.026319,22086.783272,22098.919021,-2.0,7.669039,-0.260789
2016-08-01 17:23:00,2016-08-01 17:23:00,HSI1608,22060.0,22060.0,22056.0,22060.0,2016-08-02,-8.627905,-6.720240,-1.907664,22085.055319,22097.642987,0.0,7.669039,0.000000
2016-08-01 17:24:00,2016-08-01 17:24:00,HSI1608,22061.0,22064.0,22057.0,22058.0,2016-08-02,-8.124528,-7.001098,-1.123431,22083.309815,22096.343217,-3.0,7.663478,-0.391467
2016-08-01 17:25:00,2016-08-01 17:25:00,HSI1608,22057.0,22058.0,22052.0,22052.0,2016-08-02,-8.254377,-7.251754,-1.002623,22081.289827,22094.889341,-5.0,7.653521,-0.653294
2016-08-01 17:26:00,2016-08-01 17:26:00,HSI1608,22052.0,22054.0,22041.0,22044.0,2016-08-02,-9.024972,-7.606397,-1.418575,22078.884032,22093.220838,-8.0,7.679175,-1.041779
2016-08-01 17:27:00,2016-08-01 17:27:00,HSI1608,22043.0,22051.0,22040.0,22048.0,2016-08-02,-8.566541,-7.798426,-0.768115,22076.891513,22091.738188,5.0,7.709230,0.648573
2016-08-01 17:28:00,2016-08-01 17:28:00,HSI1608,22046.0,22052.0,22046.0,22052.0,2016-08-02,-7.385444,-7.715830,0.330385,22075.285609,22090.435296,6.0,7.756914,0.773503
2016-08-01 17:29:00,2016-08-01 17:29:00,HSI1608,22052.0,22060.0,22052.0,22058.0,2016-08-02,-5.555751,-7.283814,1.728063,22074.170409,22089.371844,6.0,7.756914,0.773503
2016-08-01 17:30:00,2016-08-01 17:30:00,HSI1608,22057.0,22057.0,22051.0,22053.0,2016-08-02,-4.865024,-6.800056,1.935032,22072.804576,22088.179324,-4.0,7.655862,-0.522475
2016-08-01 17:31:00,2016-08-01 17:31:00,HSI1608,22055.0,22062.0,22055.0,22061.0,2016-08-02,-3.178759,-6.075797,2.897037,22072.042990,22087.288199,6.0,7.578845,0.791677
2016-08-01 17:32:00,2016-08-01 17:32:00,HSI1608,22063.0,22063.0,22053.0,22063.0,2016-08-02,-1.756126,-5.211863,3.455736,22071.459572,22086.491865,0.0,7.549540,0.000000
2016-08-01 17:33:00,2016-08-01 17:33:00,HSI1608,22063.0,22068.0,22059.0,22067.0,2016-08-02,-0.291628,-4.227816,3.936187,22071.171857,22085.852787,4.0,7.558862,0.529180
2016-08-01 17:34:00,2016-08-01 17:34:00,HSI1608,22066.0,22068.0,22063.0,22066.0,2016-08-02,0.474458,-3.287361,3.761819,22070.838189,22085.201876,0.0,7.547240,0.000000
2016-08-01 17:35:00,2016-08-01 17:35:00,HSI1608,22064.0,22066.0,22062.0,22066.0,2016-08-02,0.916623,-2.446564,3.363187,22070.526048,22084.572306,2.0,7.548436,0.264956
2016-08-01 17:36:00,2016-08-01 17:36:00,HSI1608,22067.0,22067.0,22060.0,22060.0,2016-08-02,0.352365,-1.886778,2.239143,22069.846948,22083.766657,-7.0,7.592741,-0.921933
2016-08-01 17:37:00,2016-08-01 17:37:00,HSI1608,22061.0,22065.0,22060.0,22065.0,2016-08-02,0.655182,-1.378386,2.033568,22069.534242,22083.151357,4.0,7.581337,0.527611
2016-08-01 17:38:00,2016-08-01 17:38:00,HSI1608,22063.0,22064.0,22060.0,22061.0,2016-08-02,0.281932,-1.046323,1.328254,22068.983645,22082.425083,-2.0,7.538991,-0.265287
2016-08-01 17:39:00,2016-08-01 17:39:00,HSI1608,22064.0,22067.0,22063.0,22066.0,2016-08-02,0.703289,-0.696400,1.399689,22068.791152,22081.886555,2.0,7.532080,0.265531
2016-08-01 17:40:00,2016-08-01 17:40:00,HSI1608,22066.0,22073.0,22066.0,22073.0,2016-08-02,1.850118,-0.187097,2.037215,22069.062691,22081.595193,7.0,7.588204,0.922484
2016-08-01 17:41:00,2016-08-01 17:41:00,HSI1608,22074.0,22074.0,22070.0,22072.0,2016-08-02,2.330065,0.316336,2.013729,22069.252195,22081.280596,-2.0,7.568575,-0.264251
2016-08-01 17:42:00,2016-08-01 17:42:00,HSI1608,22073.0,22073.0,22067.0,22069.0,2016-08-02,2.122118,0.677492,1.444626,22069.235924,22080.877954,-4.0,7.579505,-0.527739
2016-08-01 17:43:00,2016-08-01 17:43:00,HSI1608,22072.0,22072.0,22068.0,22068.0,2016-08-02,1.771288,0.896251,0.875036,22069.156187,22080.455726,-4.0,7.527929,-0.531355
2016-08-01 17:44:00,2016-08-01 17:44:00,HSI1608,22070.0,22071.0,22070.0,22070.0,2016-08-02,1.745125,1.066026,0.679099,22069.210626,22080.112915,0.0,7.442726,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-08-01 20:25:00,2016-08-01 20:25:00,HSI1608,22048.0,22048.0,22048.0,22048.0,2016-08-02,-2.336241,-1.801734,-0.534507,22054.676433,22053.563665,0.0,2.574663,0.000000
2016-08-01 20:26:00,2016-08-01 20:26:00,HSI1608,22047.0,22049.0,22046.0,22046.0,2016-08-02,-2.539310,-1.949249,-0.590061,22054.116664,22053.315676,-1.0,2.519866,-0.396847
2016-08-01 20:27:00,2016-08-01 20:27:00,HSI1608,22047.0,22053.0,22047.0,22052.0,2016-08-02,-1.759218,-1.911243,0.152025,22053.980105,22053.272539,5.0,2.571424,1.944448
2016-08-01 20:28:00,2016-08-01 20:28:00,HSI1608,22050.0,22050.0,22049.0,22049.0,2016-08-02,-1.606009,-1.850196,0.244187,22053.658808,22053.132456,-1.0,2.569641,-0.389159
2016-08-01 20:29:00,2016-08-01 20:29:00,HSI1608,22049.0,22053.0,22047.0,22053.0,2016-08-02,-0.915345,-1.663226,0.747881,22053.616304,22053.128113,4.0,2.604270,1.535939
2016-08-01 20:30:00,2016-08-01 20:30:00,HSI1608,22050.0,22051.0,22049.0,22049.0,2016-08-02,-0.985147,-1.527610,0.542463,22053.318478,22052.992765,-1.0,2.591600,-0.385862
2016-08-01 20:31:00,2016-08-01 20:31:00,HSI1608,22048.0,22051.0,22046.0,22050.0,2016-08-02,-0.852165,-1.392521,0.540356,22053.104382,22052.894642,2.0,2.558428,0.781730
2016-08-01 20:32:00,2016-08-01 20:32:00,HSI1608,22051.0,22051.0,22049.0,22049.0,2016-08-02,-0.866201,-1.287257,0.421056,22052.839584,22052.766948,-2.0,2.479023,-0.806769
2016-08-01 20:33:00,2016-08-01 20:33:00,HSI1608,22048.0,22051.0,22048.0,22051.0,2016-08-02,-0.572873,-1.144380,0.571507,22052.720901,22052.709016,3.0,2.492823,1.203455
2016-08-01 20:34:00,2016-08-01 20:34:00,HSI1608,22054.0,22055.0,22053.0,22055.0,2016-08-02,0.157067,-0.884091,1.041157,22052.867939,22052.784130,1.0,2.493102,0.401107
2016-08-01 20:35:00,2016-08-01 20:35:00,HSI1608,22055.0,22058.0,22055.0,22055.0,2016-08-02,0.591335,-0.589006,1.180341,22053.005492,22052.856781,0.0,2.471785,0.000000
2016-08-01 20:36:00,2016-08-01 20:36:00,HSI1608,22056.0,22056.0,22046.0,22046.0,2016-08-02,-0.359001,-0.543005,0.184004,22052.553525,22052.631969,-10.0,2.765813,-3.615573
2016-08-01 20:37:00,2016-08-01 20:37:00,HSI1608,22048.0,22048.0,22046.0,22046.0,2016-08-02,-0.917600,-0.617924,-0.299676,22052.130716,22052.414527,-2.0,2.779838,-0.719466
2016-08-01 20:38:00,2016-08-01 20:38:00,HSI1608,22045.0,22046.0,22041.0,22042.0,2016-08-02,-1.742353,-0.842810,-0.899543,22051.477122,22052.073067,-3.0,2.808914,-1.068028
2016-08-01 20:39:00,2016-08-01 20:39:00,HSI1608,22042.0,22044.0,22037.0,22043.0,2016-08-02,-2.032375,-1.080723,-0.951652,22050.930211,22051.775590,1.0,2.808914,0.356009
2016-08-01 20:40:00,2016-08-01 20:40:00,HSI1608,22041.0,22046.0,22041.0,22046.0,2016-08-02,-1.722723,-1.209123,-0.513601,22050.612133,22051.586226,5.0,2.876147,1.738437
2016-08-01 20:41:00,2016-08-01 20:41:00,HSI1608,22043.0,22045.0,22041.0,22043.0,2016-08-02,-1.855452,-1.338389,-0.517063,22050.121027,22051.304711,0.0,2.735111,0.000000
2016-08-01 20:42:00,2016-08-01 20:42:00,HSI1608,22041.0,22044.0,22041.0,22042.0,2016-08-02,-1.985982,-1.467907,-0.518075,22049.597090,22050.999638,1.0,2.734299,0.365725
2016-08-01 20:43:00,2016-08-01 20:43:00,HSI1608,22040.0,22043.0,22040.0,22042.0,2016-08-02,-1.977578,-1.569841,-0.407736,22049.106955,22050.704568,2.0,2.742870,0.729163
2016-08-01 20:44:00,2016-08-01 20:44:00,HSI1608,22041.0,22041.0,22040.0,22040.0,2016-08-02,-2.149308,-1.685735,-0.463574,22048.519410,22050.353599,-1.0,2.743882,-0.364447
2016-08-01 20:45:00,2016-08-01 20:45:00,HSI1608,22041.0,22043.0,22041.0,22043.0,2016-08-02,-1.763022,-1.701192,-0.061830,22048.163319,22050.112497,2.0,2.729011,0.732866
2016-08-01 20:46:00,2016-08-01 20:46:00,HSI1608,22043.0,22044.0,22034.0,22036.0,2016-08-02,-2.375134,-1.835980,-0.539153,22047.378589,22049.649792,-7.0,2.871846,-2.437457
2016-08-01 20:47:00,2016-08-01 20:47:00,HSI1608,22034.0,22034.0,22023.0,22026.0,2016-08-02,-3.959371,-2.260659,-1.698712,22045.999325,22048.874389,-8.0,3.046811,-2.625696
2016-08-01 20:48:00,2016-08-01 20:48:00,HSI1608,22025.0,22030.0,22025.0,22030.0,2016-08-02,-4.215366,-2.651600,-1.563766,22044.967110,22048.255557,5.0,3.106266,1.609650
2016-08-01 20:49:00,2016-08-01 20:49:00,HSI1608,22029.0,22031.0,22027.0,22027.0,2016-08-02,-4.580402,-3.037361,-1.543042,22043.807942,22047.558653,-2.0,3.111761,-0.642723
2016-08-01 20:50:00,2016-08-01 20:50:00,HSI1608,22030.0,22030.0,22020.0,22020.0,2016-08-02,-5.522769,-3.534442,-1.988327,22042.271946,22046.655091,-10.0,3.242256,-3.084272
2016-08-01 20:51:00,2016-08-01 20:51:00,HSI1608,22020.0,22026.0,22018.0,22026.0,2016-08-02,-5.058364,-3.839227,-1.219137,22041.222143,22045.977875,6.0,3.338995,1.796948
2016-08-01 20:52:00,2016-08-01 20:52:00,HSI1608,22022.0,22028.0,22022.0,22025.0,2016-08-02,-4.687201,-4.008821,-0.678380,22040.175553,22045.290076,3.0,3.234192,0.927589
2016-08-01 20:53:00,2016-08-01 20:53:00,HSI1608,22025.0,22026.0,22022.0,22025.0,2016-08-02,-4.256842,-4.058426,-0.198416,22039.196485,22044.624827,0.0,3.213643,0.000000
2016-08-01 20:54:00,2016-08-01 20:54:00,HSI1608,22024.0,22026.0,22022.0,22025.0,2016-08-02,-3.809620,-4.008664,0.199044,22038.280583,22043.981390,1.0,3.207803,0.311740

In [60]:
hf.get_main_contract_trade_dates('HSI1901', '20110101', '20190429')

OrderedDict()

In [208]:
d1=hf.get_bars('HSI1109',_fields)
d1

,datetime,code,open,high,low,close,trade_date
datetime,,,,,,,
2011-01-31 10:55:00,2011-01-31 10:55:00,HSI1109,22829.0,22829.0,22829.0,22829.0,2011-01-31
2011-01-31 12:29:00,2011-01-31 12:29:00,HSI1109,22839.0,22845.0,22839.0,22845.0,2011-01-31
2011-01-31 14:39:00,2011-01-31 14:39:00,HSI1109,22835.0,22835.0,22835.0,22835.0,2011-01-31
2011-01-31 14:46:00,2011-01-31 14:46:00,HSI1109,22850.0,22850.0,22850.0,22850.0,2011-01-31
2011-01-31 14:49:00,2011-01-31 14:49:00,HSI1109,22850.0,22850.0,22850.0,22850.0,2011-01-31
2011-01-31 15:13:00,2011-01-31 15:13:00,HSI1109,22931.0,22931.0,22930.0,22930.0,2011-01-31
2011-01-31 15:16:00,2011-01-31 15:16:00,HSI1109,22992.0,22992.0,22990.0,22990.0,2011-01-31
2011-01-31 15:17:00,2011-01-31 15:17:00,HSI1109,23010.0,23010.0,23010.0,23010.0,2011-01-31
2011-01-31 15:18:00,2011-01-31 15:18:00,HSI1109,22990.0,22990.0,22990.0,22990.0,2011-01-31
2011-01-31 15:27:00,2011-01-31 15:27:00,HSI1109,22950.0,22950.0,22950.0,22950.0,2011-01-31
2011-01-31 15:49:00,2011-01-31 15:49:00,HSI1109,22971.0,22971.0,22971.0,22971.0,2011-01-31
2011-01-31 15:51:00,2011-01-31 15:51:00,HSI1109,22970.0,22970.0,22970.0,22970.0,2011-01-31
2011-01-31 15:54:00,2011-01-31 15:54:00,HSI1109,22950.0,22950.0,22950.0,22950.0,2011-01-31
2011-01-31 15:55:00,2011-01-31 15:55:00,HSI1109,22950.0,22950.0,22950.0,22950.0,2011-01-31
2011-01-31 15:56:00,2011-01-31 15:56:00,HSI1109,22950.0,22950.0,22945.0,22945.0,2011-01-31
2011-01-31 16:03:00,2011-01-31 16:03:00,HSI1109,22917.0,22917.0,22917.0,22917.0,2011-01-31
2011-02-01 09:47:00,2011-02-01 09:47:00,HSI1109,22926.0,22926.0,22926.0,22926.0,2011-02-01
2011-02-01 10:03:00,2011-02-01 10:03:00,HSI1109,22899.0,22899.0,22899.0,22899.0,2011-02-01
2011-02-01 10:18:00,2011-02-01 10:18:00,HSI1109,22938.0,22938.0,22938.0,22938.0,2011-02-01
2011-02-01 10:19:00,2011-02-01 10:19:00,HSI1109,22971.0,22971.0,22971.0,22971.0,2011-02-01
2011-02-01 10:38:00,2011-02-01 10:38:00,HSI1109,22937.0,22937.0,22937.0,22937.0,2011-02-01
2011-02-01 10:55:00,2011-02-01 10:55:00,HSI1109,22946.0,22953.0,22946.0,22953.0,2011-02-01
2011-02-01 15:04:00,2011-02-01 15:04:00,HSI1109,22920.0,22920.0,22920.0,22920.0,2011-02-01
2011-02-01 15:38:00,2011-02-01 15:38:00,HSI1109,22933.0,22933.0,22933.0,22933.0,2011-02-01
2011-02-01 15:46:00,2011-02-01 15:46:00,HSI1109,22957.0,22957.0,22957.0,22957.0,2011-02-01
2011-02-01 15:50:00,2011-02-01 15:50:00,HSI1109,22953.0,22953.0,22953.0,22953.0,2011-02-01
2011-02-01 15:56:00,2011-02-01 15:56:00,HSI1109,22931.0,22931.0,22931.0,22931.0,2011-02-01
2011-02-01 16:04:00,2011-02-01 16:04:00,HSI1109,22942.0,22942.0,22942.0,22942.0,2011-02-01
2011-02-02 09:46:00,2011-02-02 09:46:00,HSI1109,23130.0,23130.0,23130.0,23130.0,2011-02-02
2011-02-02 10:03:00,2011-02-02 10:03:00,HSI1109,23150.0,23150.0,23150.0,23150.0,2011-02-02
...,...,...,...,...,...,...,...
2011-09-28 15:45:00,2011-09-28 15:45:00,HSI1109,17979.0,17989.0,17971.0,17989.0,2011-09-28
2011-09-28 15:46:00,2011-09-28 15:46:00,HSI1109,17982.0,17989.0,17963.0,17966.0,2011-09-28
2011-09-28 15:47:00,2011-09-28 15:47:00,HSI1109,17964.0,17968.0,17947.0,17948.0,2011-09-28
2011-09-28 15:48:00,2011-09-28 15:48:00,HSI1109,17948.0,17959.0,17948.0,17956.0,2011-09-28
2011-09-28 15:49:00,2011-09-28 15:49:00,HSI1109,17956.0,17968.0,17933.0,17937.0,2011-09-28
2011-09-28 15:50:00,2011-09-28 15:50:00,HSI1109,17935.0,17944.0,17925.0,17935.0,2011-09-28
2011-09-28 15:51:00,2011-09-28 15:51:00,HSI1109,17936.0,17965.0,17934.0,17965.0,2011-09-28
2011-09-28 15:52:00,2011-09-28 15:52:00,HSI1109,17963.0,17973.0,17953.0,17953.0,2011-09-28
2011-09-28 15:53:00,2011-09-28 15:53:00,HSI1109,17955.0,17959.0,17940.0,17955.0,2011-09-28
2011-09-28 15:54:00,2011-09-28 15:54:00,HSI1109,17954.0,17965.0,17944.0,17961.0,2011-09-28
2011-09-28 15:55:00,2011-09-28 15:55:00,HSI1109,17962.0,17983.0,17962.0,17981.0,2011-09-28
2011-09-28 15:56:00,2011-09-28 15:56:00,HSI1109,17983.0,18004.0,17982.0,18004.0,2011-09-28
2011-09-28 15:57:00,2011-09-28 15:57:00,HSI1109,18005.0,18015.0,17999.0,18012.0,2011-09-28
2011-09-28 15:58:00,2011-09-28 15:58:00,HSI1109,18013.0,18014.0,17981.0,17988.0,2011-09-28
2011-09-28 15:59:00,2011-09-28 15:59:00,HSI1109,17988.0,18008.0,17975.0,17994.0,2011-09-28
2011-09-28 16:00:00,2011-09-28 16:00:00,HSI1109,17991.0,18010.0,17956.0,17960.0,2011-09-28
2011-09-28 16:01:00,2011-09-28 16:01:00,HSI1109,17961.0,17976.0,17958.0,17975.0,2011-09-28
2011-09-28 16:02:00,2011-09-28 16:02:00,HSI1109,17975.0,17983.0,17966.0,17972.0,2011-09-28
2011-09-28 16:03:00,2011-09-28 16:03:00,HSI1109,17974.0,17977.0,17964.0,17967.0,2011-09-28
2011-09-28 16:04:00,2011-09-28 16:04:00,HSI1109,17966.0,17967.0,17945.0,17945.0,2011-09-28
2011-09-28 16:05:00,2011-09-28 16:05:00,HSI1109,17944.0,17958.0,17941.0,17945.0,2011-09-28
2011-09-28 16:06:00,2011-09-28 16:06:00,HSI1109,17944.0,17951.0,17928.0,17930.0,2011-09-28
2011-09-28 16:07:00,2011-09-28 16:07:00,HSI1109,17931.0,17939.0,17927.0,17937.0,2011-09-28
2011-09-28 16:08:00,2011-09-28 16:08:00,HSI1109,17935.0,17950.0,17932.0,17950.0,2011-09-28
2011-09-28 16:09:00,2011-09-28 16:09:00,HSI1109,17949.0,17970.0,17949.0,17962.0,2011-09-28
2011-09-28 16:10:00,2011-09-28 16:10:00,HSI1109,17962.0,17963.0,17941.0,17942.0,2011-09-28
2011-09-28 16:11:00,2011-09-28 16:11:00,HSI1109,17943.0,17946.0,17939.0,17940.0,2011-09-28
2011-09-28 16:12:00,2011-09-28 16:12:00,HSI1109,17940.0,17969.0,17937.0,17965.0,2011-09-28
2011-09-28 16:13:00,2011-09-28 16:13:00,HSI1109,17966.0,17970.0,17951.0,17962.0,2011-09-28
2011-09-28 16:14:00,2011-09-28 16:14:00,HSI1109,17960.0,17966.0,17940.0,17956.0,2011-09-28

In [5]:
hf.get_main_contract_trade_dates('HSI', '20110101','20190501')
HSI_Date=hf.get_main_contract_trade_dates('HSI')

In [203]:
HSI_Date['HSI1109']

[datetime.datetime(2011, 8, 31, 0, 0),
 datetime.datetime(2011, 9, 1, 0, 0),
 datetime.datetime(2011, 9, 2, 0, 0),
 datetime.datetime(2011, 9, 5, 0, 0),
 datetime.datetime(2011, 9, 6, 0, 0),
 datetime.datetime(2011, 9, 7, 0, 0),
 datetime.datetime(2011, 9, 8, 0, 0),
 datetime.datetime(2011, 9, 9, 0, 0),
 datetime.datetime(2011, 9, 12, 0, 0),
 datetime.datetime(2011, 9, 14, 0, 0),
 datetime.datetime(2011, 9, 15, 0, 0),
 datetime.datetime(2011, 9, 16, 0, 0),
 datetime.datetime(2011, 9, 19, 0, 0),
 datetime.datetime(2011, 9, 20, 0, 0),
 datetime.datetime(2011, 9, 21, 0, 0),
 datetime.datetime(2011, 9, 22, 0, 0),
 datetime.datetime(2011, 9, 23, 0, 0),
 datetime.datetime(2011, 9, 26, 0, 0),
 datetime.datetime(2011, 9, 27, 0, 0),
 datetime.datetime(2011, 9, 28, 0, 0),
 datetime.datetime(2011, 9, 29, 0, 0),
 datetime.datetime(2011, 9, 30, 0, 0)]

In [120]:
for i in dl['HSI1904']:
    print(i)

2019-03-29 00:00:00
2019-04-01 00:00:00
2019-04-02 00:00:00
2019-04-03 00:00:00
2019-04-04 00:00:00
2019-04-08 00:00:00
2019-04-09 00:00:00
2019-04-10 00:00:00
2019-04-11 00:00:00
2019-04-12 00:00:00
2019-04-15 00:00:00
2019-04-16 00:00:00
2019-04-17 00:00:00
2019-04-18 00:00:00
2019-04-23 00:00:00
2019-04-24 00:00:00
2019-04-25 00:00:00
2019-04-26 00:00:00
2019-04-29 00:00:00

In [99]:
dt1=hf.get_bars(ll[0],_fields)
dt1.trade_date.unique()[0]

numpy.datetime64('2011-01-03T00:00:00.000000000')

In [105]:
date1=HSI_Date['HSI1904'][1]
d1[str(date1.date())]
print(date1)
print(date1.date())
d1[str(date1.date())]
d1.resample('B').min()

2019-04-01 00:00:00
2019-04-01

,datetime,code,open,high,low,close,trade_date
datetime,,,,,,,
2019-02-28,2019-02-28 09:21:00,HSI1904,28600.0,28600.0,28600.0,28600.0,2019-02-28
2019-03-01,2019-03-01 09:33:00,HSI1904,28719.0,28719.0,28719.0,28719.0,2019-03-01
2019-03-04,2019-03-04 09:15:00,HSI1904,28791.0,28797.0,28774.0,28774.0,2019-03-04
2019-03-05,2019-03-05 09:19:00,HSI1904,28726.0,28726.0,28726.0,28726.0,2019-03-05
2019-03-06,2019-03-06 09:15:00,HSI1904,28909.0,28909.0,28909.0,28909.0,2019-03-06
2019-03-07,2019-03-07 09:15:00,HSI1904,28765.0,28765.0,28765.0,28765.0,2019-03-07
2019-03-08,2019-03-08 09:15:00,HSI1904,28215.0,28215.0,28215.0,28215.0,2019-03-08
2019-03-11,2019-03-11 09:15:00,HSI1904,28188.0,28188.0,28188.0,28188.0,2019-03-11
2019-03-12,2019-03-12 09:15:00,HSI1904,28760.0,28781.0,28760.0,28781.0,2019-03-12
2019-03-13,2019-03-13 09:15:00,HSI1904,28745.0,28745.0,28745.0,28745.0,2019-03-13
2019-03-14,2019-03-14 09:15:00,HSI1904,28722.0,28722.0,28713.0,28721.0,2019-03-14
2019-03-15,2019-03-15 09:15:00,HSI1904,28877.0,28878.0,28877.0,28878.0,2019-03-15
2019-03-18,2019-03-18 09:15:00,HSI1904,29101.0,29110.0,29101.0,29107.0,2019-03-18
2019-03-19,2019-03-19 09:15:00,HSI1904,29380.0,29385.0,29380.0,29385.0,2019-03-19
2019-03-20,2019-03-20 09:15:00,HSI1904,29308.0,29308.0,29308.0,29308.0,2019-03-20
2019-03-21,2019-03-21 09:15:00,HSI1904,29122.0,29122.0,29122.0,29122.0,2019-03-21
2019-03-22,2019-03-22 09:15:00,HSI1904,28893.0,28893.0,28887.0,28887.0,2019-03-22
2019-03-25,2019-03-25 09:15:00,HSI1904,28473.0,28488.0,28466.0,28478.0,2019-03-25
2019-03-26,2019-03-26 09:15:00,HSI1904,28468.0,28476.0,28460.0,28469.0,2019-03-26
2019-03-27,2019-03-27 09:15:00,HSI1904,28598.0,28605.0,28588.0,28596.0,2019-03-27
2019-03-28,2019-03-28 09:15:00,HSI1904,28588.0,28605.0,28575.0,28587.0,2019-03-28
2019-03-29,2019-03-29 09:15:00,HSI1904,28786.0,28803.0,28771.0,28785.0,2019-03-29
2019-04-01,2019-04-01 09:15:00,HSI1904,29427.0,29434.0,29415.0,29426.0,2019-04-01
2019-04-02,2019-04-02 00:00:00,HSI1904,29592.0,29599.0,29583.0,29592.0,2019-04-02
2019-04-03,2019-04-03 00:00:00,HSI1904,29686.0,29688.0,29681.0,29688.0,2019-04-03
2019-04-04,2019-04-04 00:00:00,HSI1904,29827.0,29829.0,29810.0,29826.0,2019-04-04
2019-04-05,2019-04-05 00:00:00,HSI1904,30052.0,30063.0,30050.0,30051.0,2019-04-08
2019-04-08,2019-04-08 09:15:00,HSI1904,29968.0,29978.0,29965.0,29968.0,2019-04-08
2019-04-09,2019-04-09 00:00:00,HSI1904,30074.0,30092.0,30071.0,30075.0,2019-04-09
2019-04-10,2019-04-10 00:00:00,HSI1904,29954.0,29964.0,29944.0,29952.0,2019-04-10
2019-04-11,2019-04-11 00:00:00,HSI1904,29805.0,29810.0,29795.0,29805.0,2019-04-11
2019-04-12,2019-04-12 00:00:00,HSI1904,29716.0,29732.0,29706.0,29716.0,2019-04-12
2019-04-15,2019-04-15 09:15:00,HSI1904,29688.0,29700.0,29684.0,29688.0,2019-04-15
2019-04-16,2019-04-16 00:00:00,HSI1904,29693.0,29697.0,29691.0,29692.0,2019-04-16
2019-04-17,2019-04-17 00:00:00,HSI1904,30014.0,30027.0,30008.0,30015.0,2019-04-17
2019-04-18,2019-04-18 00:00:00,HSI1904,29893.0,29905.0,29882.0,29894.0,2019-04-18
2019-04-19,2019-04-19 00:00:00,HSI1904,30070.0,30075.0,30070.0,30070.0,2019-04-23
2019-04-22,NaT,NaN,NaN,NaN,NaN,NaN,NaT
2019-04-23,2019-04-23 09:15:00,HSI1904,29761.0,29780.0,29742.0,29763.0,2019-04-23
2019-04-24,2019-04-24 00:00:00,HSI1904,29655.0,29677.0,29650.0,29655.0,2019-04-24
2019-04-25,2019-04-25 00:00:00,HSI1904,29413.0,29423.0,29412.0,29415.0,2019-04-25
2019-04-26,2019-04-26 00:00:00,HSI1904,29450.0,29499.0,29447.0,29496.0,2019-04-26
2019-04-29,2019-04-29 09:15:00,HSI1904,29633.0,29650.0,29628.0,29633.0,2019-04-29

In [116]:
LL=HSI_Date['HSI1904']
for i in LL:
    print(i)

2019-03-29 00:00:00
2019-04-01 00:00:00
2019-04-02 00:00:00
2019-04-03 00:00:00
2019-04-04 00:00:00
2019-04-08 00:00:00
2019-04-09 00:00:00
2019-04-10 00:00:00
2019-04-11 00:00:00
2019-04-12 00:00:00
2019-04-15 00:00:00
2019-04-16 00:00:00
2019-04-17 00:00:00
2019-04-18 00:00:00
2019-04-23 00:00:00
2019-04-24 00:00:00
2019-04-25 00:00:00
2019-04-26 00:00:00
2019-04-29 00:00:00

In [75]:
dt1=dt.time(9,15)
dt2=dt.time(16,30)
dt2
day_only=bar1.datetime.apply(lambda x:x.time()>=dt1 and x.time()<=dt1 )
bar2=bar1[day_only]
bar1

,datetime,code,open,high,low,close,volume,trade_date,time
datetime,,,,,,,,,
2019-04-02 17:15:00,2019-04-02 17:15:00,HSI1904,29737.0,29743.0,29704.0,29711.0,264.0,2019-04-03,17:15:00
2019-04-02 17:16:00,2019-04-02 17:16:00,HSI1904,29710.0,29723.0,29709.0,29720.0,85.0,2019-04-03,17:16:00
2019-04-02 17:17:00,2019-04-02 17:17:00,HSI1904,29720.0,29724.0,29718.0,29721.0,73.0,2019-04-03,17:17:00
2019-04-02 17:18:00,2019-04-02 17:18:00,HSI1904,29720.0,29722.0,29717.0,29721.0,71.0,2019-04-03,17:18:00
2019-04-02 17:19:00,2019-04-02 17:19:00,HSI1904,29722.0,29727.0,29721.0,29722.0,78.0,2019-04-03,17:19:00
2019-04-02 17:20:00,2019-04-02 17:20:00,HSI1904,29721.0,29723.0,29720.0,29722.0,32.0,2019-04-03,17:20:00
2019-04-02 17:21:00,2019-04-02 17:21:00,HSI1904,29721.0,29724.0,29721.0,29721.0,20.0,2019-04-03,17:21:00
2019-04-02 17:22:00,2019-04-02 17:22:00,HSI1904,29722.0,29726.0,29719.0,29725.0,38.0,2019-04-03,17:22:00
2019-04-02 17:23:00,2019-04-02 17:23:00,HSI1904,29726.0,29727.0,29724.0,29724.0,34.0,2019-04-03,17:23:00
2019-04-02 17:24:00,2019-04-02 17:24:00,HSI1904,29724.0,29728.0,29724.0,29728.0,43.0,2019-04-03,17:24:00
2019-04-02 17:25:00,2019-04-02 17:25:00,HSI1904,29727.0,29729.0,29723.0,29724.0,66.0,2019-04-03,17:25:00
2019-04-02 17:26:00,2019-04-02 17:26:00,HSI1904,29725.0,29725.0,29717.0,29723.0,60.0,2019-04-03,17:26:00
2019-04-02 17:27:00,2019-04-02 17:27:00,HSI1904,29724.0,29727.0,29721.0,29726.0,65.0,2019-04-03,17:27:00
2019-04-02 17:28:00,2019-04-02 17:28:00,HSI1904,29726.0,29731.0,29726.0,29730.0,55.0,2019-04-03,17:28:00
2019-04-02 17:29:00,2019-04-02 17:29:00,HSI1904,29730.0,29732.0,29726.0,29728.0,51.0,2019-04-03,17:29:00
2019-04-02 17:30:00,2019-04-02 17:30:00,HSI1904,29729.0,29729.0,29723.0,29726.0,20.0,2019-04-03,17:30:00
2019-04-02 17:31:00,2019-04-02 17:31:00,HSI1904,29725.0,29726.0,29721.0,29721.0,21.0,2019-04-03,17:31:00
2019-04-02 17:32:00,2019-04-02 17:32:00,HSI1904,29721.0,29726.0,29721.0,29724.0,37.0,2019-04-03,17:32:00
2019-04-02 17:33:00,2019-04-02 17:33:00,HSI1904,29723.0,29724.0,29721.0,29723.0,25.0,2019-04-03,17:33:00
2019-04-02 17:34:00,2019-04-02 17:34:00,HSI1904,29725.0,29726.0,29725.0,29726.0,19.0,2019-04-03,17:34:00
2019-04-02 17:35:00,2019-04-02 17:35:00,HSI1904,29724.0,29724.0,29720.0,29720.0,24.0,2019-04-03,17:35:00
2019-04-02 17:36:00,2019-04-02 17:36:00,HSI1904,29720.0,29724.0,29720.0,29722.0,61.0,2019-04-03,17:36:00
2019-04-02 17:37:00,2019-04-02 17:37:00,HSI1904,29725.0,29728.0,29724.0,29727.0,52.0,2019-04-03,17:37:00
2019-04-02 17:38:00,2019-04-02 17:38:00,HSI1904,29726.0,29730.0,29726.0,29728.0,33.0,2019-04-03,17:38:00
2019-04-02 17:39:00,2019-04-02 17:39:00,HSI1904,29728.0,29730.0,29727.0,29729.0,29.0,2019-04-03,17:39:00
2019-04-02 17:40:00,2019-04-02 17:40:00,HSI1904,29728.0,29735.0,29725.0,29726.0,66.0,2019-04-03,17:40:00
2019-04-02 17:41:00,2019-04-02 17:41:00,HSI1904,29726.0,29727.0,29723.0,29725.0,13.0,2019-04-03,17:41:00
2019-04-02 17:42:00,2019-04-02 17:42:00,HSI1904,29725.0,29726.0,29723.0,29723.0,9.0,2019-04-03,17:42:00
2019-04-02 17:43:00,2019-04-02 17:43:00,HSI1904,29723.0,29732.0,29723.0,29729.0,65.0,2019-04-03,17:43:00
2019-04-02 17:44:00,2019-04-02 17:44:00,HSI1904,29728.0,29729.0,29727.0,29727.0,21.0,2019-04-03,17:44:00
...,...,...,...,...,...,...,...,...,...
2019-04-29 15:27:00,2019-04-29 15:27:00,HSI1904,29814.0,29815.0,29814.0,29815.0,7.0,2019-04-29,15:27:00
2019-04-29 15:28:00,2019-04-29 15:28:00,HSI1904,29815.0,29816.0,29815.0,29816.0,8.0,2019-04-29,15:28:00
2019-04-29 15:29:00,2019-04-29 15:29:00,HSI1904,29815.0,29815.0,29815.0,29815.0,9.0,2019-04-29,15:29:00
2019-04-29 15:30:00,2019-04-29 15:30:00,HSI1904,29815.0,29816.0,29814.0,29816.0,10.0,2019-04-29,15:30:00
2019-04-29 15:31:00,2019-04-29 15:31:00,HSI1904,29816.0,29816.0,29815.0,29816.0,9.0,2019-04-29,15:31:00
2019-04-29 15:32:00,2019-04-29 15:32:00,HSI1904,29815.0,29817.0,29815.0,29817.0,34.0,2019-04-29,15:32:00
2019-04-29 15:33:00,2019-04-29 15:33:00,HSI1904,29816.0,29816.0,29816.0,29816.0,3.0,2019-04-29,15:33:00
2019-04-29 15:34:00,2019-04-29 15:34:00,HSI1904,29817.0,29817.0,29813.0,29814.0,102.0,2019-04-29,15:34:00
2019-04-29 15:35:00,2019-04-29 15:35:00,HSI1904,29813.0,29814.0,29813.0,29814.0,5.0,2019-04-29,15:35:00
2019-04-29 15:36:00,2019-04-29 15:36:00,HSI1904,29814.0,29814.0,29814.0,29814.0,11.0,2019-04-29,15:36:00
2019-04-29 15:37:00,2019-04-29 15:37:00,HSI1904,29813.0,29814.0,29813.0,29814.0,15.0,2019-04-29,15:37:00
2019-04-29 15:38:00,2019-04-29 15:38:00,HSI1904,29814.0,29814.0,29813.0,29813.0,18.0,2019-04-29,15:38:00
2019-04-29 15:39:00,2019-04-29 15:39:00,HSI1904,29813.0,29815.0,29813.0,29814.0,29.0,2019-04-29,15:39:00
2019-04-29 15:40:00,2019-04-29 15:40:00,HSI1904,29814.0,29814.0,29813.0,29813.0,60.0,2019-04-29,15:40:00
2019-04-29 15:41:00,2019-04-29 15:41:00,HSI1904,29813.0,29814.0,29813.0,29814.0,32.0,2019-04-29,15:41:00
2019-04-29 15:42:00,2019-04-29 15:42:00,HSI1904,29814.0,29814.0,29813.0,29814.0,120.0,2019-04-29,15:42:00
2019-04-29 15:43:00,2019-04-29 15:43:00,HSI1904,29815.0,29815.0,29813.0,29813.0,301.0,2019-04-29,15:43:00
2019-04-29 15:44:00,2019-04-29 15:44:00,HSI1904,29816.0,29816.0,29816.0,29816.0,8.0,2019-04-29,15:44:00
2019-04-29 15:45:00,2019-04-29 15:45:00,HSI1904,29818.0,29818.0,29818.0,29818.0,1.0,2019-04-29,15:45:00
2019-04-29 15:46:00,2019-04-29 15:46:00,HSI1904,29817.0,29817.0,29816.0,29816.0,4.0,2019-04-29,15:46:00
2019-04-29 15:47:00,2019-04-29 15:47:00,HSI1904,29817.0,29818.0,29816.0,29817.0,29.0,2019-04-29,15:47:00
2019-04-29 15:50:00,2019-04-29 15:50:00,HSI1904,29818.0,29818.0,29818.0,29818.0,3.0,2019-04-29,15:50:00
2019-04-29 15:51:00,2019-04-29 15:51:00,HSI1904,29818.0,29818.0,29817.0,29818.0,6.0,2019-04-29,15:51:00
2019-04-29 15:52:00,2019-04-29 15:52:00,HSI1904,29818.0,29818.0,29818.0,29818.0,4.0,2019-04-29,15:52:00
2019-04-29 15:53:00,2019-04-29 15:53:00,HSI1904,29818.0,29818.0,29818.0,29818.0,2.0,2019-04-29,15:53:00
2019-04-29 15:54:00,2019-04-29 15:54:00,HSI1904,29817.0,29817.0,29816.0,29816.0,20.0,2019-04-29,15:54:00
2019-04-29 15:56:00,2019-04-29 15:56:00,HSI1904,29818.0,29818.0,29817.0,29818.0,43.0,2019-04-29,15:56:00
2019-04-29 15:57:00,2019-04-29 15:57:00,HSI1904,29818.0,29818.0,29817.0,29817.0,2.0,2019-04-29,15:57:00
2019-04-29 15:58:00,2019-04-29 15:58:00,HSI1904,29818.0,29818.0,29817.0,29818.0,9.0,2019-04-29,15:58:00
2019-04-29 15:59:00,2019-04-29 15:59:00,HSI1904,29818.0,29818.0,29818.0,29818.0,39.0,2019-04-29,15:59:00

In [106]:
hf.get_bars('HSI1904',end=bar2.iloc[0]['datetime'],bar_counts=2)

,datetime,code,open,high,low,close,volume,trade_date
datetime,,,,,,,,
2019-04-03 00:59:00,2019-04-03 00:59:00,HSI1904,29723.0,29731.0,29722.0,29724.0,44.0,2019-04-03
2019-04-03 09:15:00,2019-04-03 09:15:00,HSI1904,29787.0,29799.0,29760.0,29793.0,1396.0,2019-04-03

In [188]:
def a(t=['1','2','3']):
    print(t)
    
a()

['1', '2', '3']